MERGE INTO GENRE VALUES ( 1, 'COMEDY');
MERGE INTO GENRE VALUES ( 2, 'DRAMA');
MERGE INTO GENRE VALUES ( 3, 'ANIMATION');
MERGE INTO GENRE VALUES ( 4, 'THRILLER');
MERGE INTO GENRE VALUES ( 5, 'DOCUMENTARY');
MERGE INTO GENRE VALUES ( 6, 'ACTION');

MERGE INTO MPA_RATING VALUES ( 1, 'G' );
MERGE INTO MPA_RATING VALUES ( 2, 'PG' );
MERGE INTO MPA_RATING VALUES ( 3, 'PG13' );
MERGE INTO MPA_RATING VALUES ( 4, 'R' );
MERGE INTO MPA_RATING VALUES ( 5, 'NC17' );